fileVersion: 1
id: 0eb41f90-c63f-4c43-8eaa-1d6756d60006
name: HUB_POLICY_PREM_VALUES
operation:
  config:
    disable_hwm: true
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: WORK
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e34270a4-7a54-4486-9388-da0630b1ce87
          stepCounter: 0eb41f90-c63f-4c43-8eaa-1d6756d60006
        config: {}
        dataType: TIMESTAMP
        description: The Load Date Timestamp (LDTS) describes when this data first arrived in the Data Warehouse.
        name: LDTS
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 0f7c7384-ab70-4372-96b3-7a7cc7c69ffa
                stepCounter: b6771cc7-83b3-4a92-a15a-bab07b79bfb7
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7efa4c35-a6b3-4cc5-8787-e322782d87a3
          stepCounter: 0eb41f90-c63f-4c43-8eaa-1d6756d60006
        config: {}
        dataType: STRING
        description: The Record Source (RSRC) describes the source of this data.
        name: RSRC
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 9d508fdb-4c3d-4261-9a9b-3e1f5cd9e500
                stepCounter: b6771cc7-83b3-4a92-a15a-bab07b79bfb7
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5566e2f2-3868-4f22-a95c-04c1f8e38f5f
          stepCounter: 0eb41f90-c63f-4c43-8eaa-1d6756d60006
        config: {}
        dataType: VARCHAR(36)
        description: ""
        name: PPV_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 091d0117-a431-4b90-9f7c-176124fc52d1
                stepCounter: b6771cc7-83b3-4a92-a15a-bab07b79bfb7
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a2d8d044-7228-4b70-b157-6e4beb0352a4
          stepCounter: 0eb41f90-c63f-4c43-8eaa-1d6756d60006
        config:
          is_Hub_hk: true
        dataType: STRING
        description: ""
        name: H_PPV_KEY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 03342f68-ad12-401c-946b-bbcda2610726
                stepCounter: b6771cc7-83b3-4a92-a15a-bab07b79bfb7
            transform: ""
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          DVSTG_POLICY_PREM_VALUES: b6771cc7-83b3-4a92-a15a-bab07b79bfb7
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: WORK
            nodeName: DVSTG_POLICY_PREM_VALUES
        join:
          joinCondition: FROM {{ ref('WORK', 'DVSTG_POLICY_PREM_VALUES') }} "DVSTG_POLICY_PREM_VALUES"
        name: HUB_POLICY_PREM_VALUES
        noLinkRefs: []
  name: HUB_POLICY_PREM_VALUES
  overrideSQL: false
  schema: ""
  sqlType: dv:::6
  type: sql
  version: 1
type: Node
